MxOnline/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from users.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static
from organization.views import TeacherListView
from django.views.static import serve
import xadmin

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    # url(r'^xadmin/', xadmin.site.urls),
    url(r'^index/$', HomePageView.as_view(), name='homepage'),
    url(r'^$', HomePageView.as_view(), name='homepage'),
    url(r'^captcha/', include('captcha.urls')),

    url(r'^user/', include('users.urls', namespace='users')),
    url(r'^course/', include('courses.urls', namespace='courses')),
    url(r'^org/', include('organization.urls', namespace='orgs')),
    url(r'^operation/', include('operation.urls', namespace='operation')),
    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),
    # ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    url(r'^ueditor/',include('DjangoUeditor.urls' )),
]

if settings.DEBUG:
    # 在开发模式下，用户上传到media文件夹的文件可以按照设定的路径查找，但仅限于开发模式；
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]
else:
    # 保证项目固定的静态文件可以正常加载,按照设定的路径查找；
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

apps/courses/urls.py
from django.conf.urls import url, include
from .views import CourseListView, CourseDetailView, CourseVideoView, VideoPlayView, CourseCommentView, AddCommentView



urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name='course_list'),  # 视频列表页
    url(r'^(?P<course_id>.*)/detail/$', CourseDetailView.as_view(), name='course_detail'),  # 课程详情
    url(r'^(?P<course_id>.*)/videos/$', CourseVideoView.as_view(), name='course_videos'),   # 课程视频列表
    url(r'^(?P<course_id>.*)/play_videos/(?P<video_id>.*)/$', VideoPlayView.as_view(), name='play_videos'), # 视频播放页面

    url(r'^(?P<course_id>.*)/comment/$', CourseCommentView.as_view(), name='course_comment'),  # 指定的课程评论列表页面
    url(r'^add_comment/$', AddCommentView.as_view(), name='add_comment'),  # 评论当前课程

]

apps/organization/urls.py
from django.conf.urls import url, include
from .views import OrgListView, TeacherListView
from .views import OrgHomePage, OrgCourseView, OrgDescriptionView, OrgTeachersView, AddFavorView, TeacherDetailView


urlpatterns = [
    #机构页面相关的url配置
    url(r'^list/$', OrgListView.as_view(), name='org_list'),    # 机构列表页
    url(r'^home/(?P<org_id>[0-9]+)/$', OrgHomePage.as_view(), name='org_homepage'), # 机构详情页主页面
    url(r'^courses/(?P<org_id>[0-9]+)/$', OrgCourseView.as_view(), name='courses'), # 机构课程
    url(r'^des/(?P<org_id>[0-9]+)/$', OrgDescriptionView.as_view(), name='description'), #机构简介
    url(r'^teachers/(?P<org_id>[0-9]+)/$', OrgTeachersView.as_view(), name='teachers'), #机构的教师列表

    #教师页面相关的url配置
    url(r'^teacher_detail/(?P<teacher_id>[0-9]+)/$', TeacherDetailView.as_view(), name='teacher_detail'),


    url(r'^add_fav/$', AddFavorView.as_view(), name='add_favor'),


]

apps/users/urls.py
from django.conf.urls import url
from .views import LoginView, logout_user, RegisterView, ActivateUserView, active_fail, active_success, ForgetPwdView, \
    ResetPwdView, UserCenterInfoView, SendEmailCodeView, ChangeEmailView, ChangePwdView, ImageUploadView, MyCourseView, \
    UserFavorCourseView, UserFavorTeachersView, UserFavorOrgsView, UserMessagesView



urlpatterns = [
    url('^login/$', LoginView.as_view(), name='login'),  # 用户登录
    url('^register/$', RegisterView.as_view(), name='register'),  # 注册新用户
    url('^logout/$', logout_user, name='logout'), # 注销当前用户
    url('^activate/(?P<code>.{16})/$', ActivateUserView.as_view(), name='activate'),#激活用户

    url('^active_failed/$', active_fail, name='active_failed'),
    url('^active_success/$', active_success, name='active_success'),

    url('^forget_pwd/$', ForgetPwdView.as_view(), name='forget_pwd'), # 登录页面忘记密码
    url('^reset_pwd/$', ResetPwdView.as_view(), name='reset_pwd'),  # 重置密码

    #在用户中心进行的相关操作
    url('^send_email_code/$', SendEmailCodeView.as_view(), name='send_email_code'),  # 发送邮箱验证码
    url('^change_email/$', ChangeEmailView.as_view(), name='change_mail'),
    url('^change_password/$', ChangePwdView.as_view(), name='change_pwd'),  # 修改密码
    url('^image_upload/$', ImageUploadView.as_view(), name='change_image'),  # 修改图片
    url('^user_course/$', MyCourseView.as_view(), name='user_course'),    # 用户学习课程

    url('^info/$', UserCenterInfoView.as_view(), name='user_center'),
    url('^favor/course/$', UserFavorCourseView.as_view(), name='fav_course'),  # 用户收藏课程
    url('^favor/orgs/$', UserFavorOrgsView.as_view(), name='fav_orgs'),  # 用户收藏机构
    url('^favor/teachers/$', UserFavorTeachersView.as_view(), name='fav_teachers'),  # 用户收藏教师
    url('^messages/$', UserMessagesView.as_view(), name='user_messages'),  # 用户消息

]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/courses/models.py
from datetime import datetime
from django.db import models
from organization.models import CourseOrg, Teacher
from DjangoUeditor.models import UEditorField
from django.utils.safestring import mark_safe


class Course(models.Model):
    name = models.CharField(max_length=50, verbose_name='课程名')
    description = models.CharField(max_length=100, verbose_name='课程描述')
    # detail = models.TextField(verbose_name='课程详情')
    # 配置ueditor
    detail = UEditorField(verbose_name='课程详情', width=600, height=300, imagePath="courses/ueditor/",
                            filePath="courses/ueditor/",default='')

    degree = models.CharField(choices=(('CJ', '初级'), ('ZJ', '中级'), ('GJ', '高级')), max_length=10)
    learn_times = models.IntegerField(default=0, verbose_name='学习时长(分钟)')
    students_num = models.IntegerField(default=0, verbose_name='学习人数')
    category = models.CharField(max_length=20, verbose_name='课程类别')
    favor_num = models.IntegerField(default=0, verbose_name='收藏数')
    org = models.ForeignKey(CourseOrg, verbose_name="所属课程机构")
    image = models.ImageField(upload_to="course/%Y/%m", verbose_name='课程图片', max_length=100)
    click_num = models.IntegerField(default=0, verbose_name='点击数')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='课程添加时间')
    teacher = models.ForeignKey(Teacher, verbose_name="授课教师", blank=True, null=True)
    recommend = models.BooleanField(default=False, verbose_name='是否推荐', max_length=2)
    has_favor = models.BooleanField(default=False, verbose_name='是否收藏')
    notice = models.CharField(default='', verbose_name='课程须知', max_length=200)
    is_banner = models.BooleanField(default=False, verbose_name='广告课程')

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name
        db_table = '课程'

    def __str__(self):
        return self.name

    def get_chap_num(self):
        return self.chapter_set.all().count()

    get_chap_num.short_description='章节数'

    def my_link(self):
        return mark_safe('<a href="https://www.baidu.com">链接</a>')
    my_link.short_description='章节数'


class Chapter(models.Model):
    name = models.CharField(max_length=50, verbose_name='章节名')
    course = models.ForeignKey(Course, verbose_name='所属课程')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='课程添加时间')

    class Meta:
        verbose_name = '章节'
        verbose_name_plural = verbose_name
        db_table = '章节'

    def __str__(self):
        return self.name


class Video(models.Model):
    name = models.CharField(max_length=50, verbose_name='视频名')
    chapter = models.ForeignKey(Chapter, verbose_name='所属章节')
    url = models.URLField(max_length=200, verbose_name='视频链接')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='课程添加时间')

    class Meta:
        verbose_name = '视频'
        verbose_name_plural = verbose_name
        db_table = '视频'

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    name = models.CharField(max_length=30, verbose_name='资料名称')
    course = models.ForeignKey(Course)
    download = models.FileField(upload_to='course/download/%Y/%m', verbose_name='下载', max_length=100)

    class Meta:
        verbose_name = '课程资源下载'
        verbose_name_plural = verbose_name
        db_table = '课程资源下载'

    def __str__(self):
        return self.name

apps/users/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser


class UserProfile(AbstractUser):
    nick_name = models.CharField(max_length=20, verbose_name='昵称')
    birthday = models.DateField(max_length=20, verbose_name='生日', null=True, blank=True)
    gender = models.CharField(max_length=20, choices=(('male', "男"),("female", "女")), verbose_name='性别')
    address = models.CharField(max_length=100, verbose_name='住址', null=True, blank=True)
    mobile = models.CharField(max_length=11, verbose_name='联系电话', null=True, blank=True)
    image = models.ImageField(upload_to="image/%Y/%m", default="image/default.png", max_length=100)

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name
        db_table='用户信息'

    def __str__(self):
        return self.username
    #
    # def get_unread_msg_num(self):
    #     from operation.models import UserMessages
    #     if UserMessages.objects.filter(user=self, has_read=False):
    #         return len(UserMessages.objects.filter(user=self, has_read=False))
    #     else:
    #         return 0


class EmailVerifyRecord(models.Model):
    code = models.CharField(max_length=20, verbose_name='验证码')
    email = models.EmailField(max_length=50, verbose_name='邮箱')
    send_type = models.CharField(choices=(('register', '注册'), ('forget', '找回密码'), ('reset_password', '重置密码')), max_length=20)
    send_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间') #不能加括号，否则就是显示的时间是model注册的时间

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = verbose_name
        db_table='邮箱验证码'

    def __str__(self):
        return self.code


class Banner(models.Model):
    title = models.CharField(max_length=100, verbose_name='标题')
    image = models.ImageField(upload_to='banner/%Y/%m', verbose_name='轮播图', max_length=100)
    url = models.URLField(max_length=200, verbose_name='访问地址')
    index = models.IntegerField(default=100, verbose_name="序号")
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name
        db_table='轮播图'

    def __str__(self):
        return self.title

apps/users/forms.py
from django import forms
from captcha.fields import CaptchaField


class LoginForms(forms.Form):
    password = forms.CharField(min_length=6, max_length=20, label='密码', required=True)
    username = forms.CharField(min_length=1, required=True, label='用户名', widget=forms.Textarea)





from django.forms import ValidationError
from users.models import UserProfile


class RegisterForms(forms.Form):
    username = forms.CharField(min_length=2, max_length=30,
                               error_messages={'required': '用户名不能为空', 'min_length': '用户名至少为两位'})
    password1 = forms.CharField(min_length=6, max_length=12,
                                error_messages={'required': '密码不能为空', 'min_length': '密码至少为两位'})
    password2 = forms.CharField(min_length=6, max_length=12,
                                error_messages={'required': '密码不能为空', 'min_length': '密码名至少为两位'})
    captcha = CaptchaField()

    def clean_username(self):
        username = self.cleaned_data['username'].strip()
        if UserProfile.objects.filter(username=username):
            raise ValidationError("用户已注册")
        return username

    def clean(self):
        """密码一致性检测"""
        if self.cleaned_data.get('password1', '') == self.cleaned_data.get('password2', ''):
            return self.cleaned_data
        else:
            raise ValidationError("密码不一致")


class ForgetPwdForms(forms.Form):
    username = forms.CharField(max_length=30, error_messages={'required': '用户名不能为空'})
    captcha = CaptchaField()

    def clean_username(self):
        username = self.cleaned_data['username'].strip()
        if not UserProfile.objects.filter(username=username):
            raise ValidationError("用户不存在")
        return username


class ResetPwdForms(forms.Form):
    password1 = forms.CharField(min_length=6, max_length=30)
    password2 = forms.CharField(min_length=6, max_length=30)
    # username = forms.CharField(max_length=30)

    def clean(self):
        """密码一致性检测"""
        if self.cleaned_data.get('password1', '') == self.cleaned_data.get('password2', ''):
            return self.cleaned_data

        else:
            raise ValidationError("密码不一致")


class ModifyEmailForm(forms.Form):
    email = forms.EmailField(max_length=30, min_length=3)
    code = forms.CharField(min_length=4, max_length=4)

    # # 可以使用全局钩子验证
    # def clean(self):
    #     from apps.users.models import EmailVerifyRecord
    #     if not EmailVerifyRecord.objects.filter(email=self.email, code=self.code,send_type='change_email'):
    #         raise ValidationError('邮箱或验证码不匹配')
    #     else:
    #         return self.cleaned_data



class UploadImageForm(forms.Form):
    image = forms.ImageField(max_length=100)

apps/users/templates/usercenter-message.html
{% extends 'usercenter-info.html' %}
{% load static %}

{% block title %}我的消息- 学习在线{% endblock %}

{% block bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'homepage' %}">首页</a>></li>
            <li><a href="{% url 'users:user_center' %}">个人中心</a>></li>
            <li>我的消息</li>
        </ul>
    </div>
</section>

{% endblock %}

{% block content %}
    <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的消息</h1>
			</div>
		</div>

		<div class="personal_des permessage">

			<div class="head">
				<ul class="tab_header messagehead">
					<li class="active"><a href="/user/message/">个人消息</a> </li>
				</ul>
			</div>

			<div class="messagelist">
                {% for msg in user_msgs.object_list %}
                    <div class="messages">
                        <div class="fr">
                            <div class="top"><span class="fl time">{{ msg.add_time }}</span><span class="fr btn foldbtn"></span></div>
                            <p>
                                {{ msg.message }}
                            </p>
                        </div>
                    </div>
                {% endfor %}
			</div>

			<div class="pageturn">
                  <ul class="pagelist">
                        {% load i18n %}
                            {% if user_msgs.has_previous %}
                                {# 有上一页就不显示这个 #}
                                <li class="long"><a href="?{{ user_msgs.previous_page_number.querystring }}" >&lsaquo;&lsaquo; {% trans "上一页" %}</a></li>
                            {% endif %}

                            {% for page in user_msgs.pages %}
                                {# 循环遍历每一页 #}
                                {% if page %}
                                    {% ifequal page user_msgs.number %}
                                        {# 如果是当前页 #}
                                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                    {% else %}
                                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                    {% endifequal %}

                                {% else %}
                                    <li class="none"><a href="">/static.</a></li>

                                {% endif %}
                            {% endfor %}

                            {% if user_msgs.has_next %}
                                <li class="long"><a href="?{{ user_msgs.next_page_number.querystring }}" >&lsaquo;&lsaquo; {% trans "下一页" %}</a></li>
                            {% endif %}

                        </ul>
            </div>

		</div>

	</div>
{% endblock %}

apps/users/templates/usercenter-mycourse.html
{% extends 'usercenter-info.html' %}
{% load static %}

{% block title %}我的课程- 学习在线{% endblock %}

{% block bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'homepage' %}">首页</a>></li>
            <li><a href="{% url 'users:user_center' %}">个人中心</a>></li>
            <li>我的课程</li>
        </ul>
    </div>
</section>

{% endblock %}

{% block content %}
<div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的课程</h1>
			</div>
		</div>
		<div class="personal_des permessage">
			<div class="companycenter">
				<div class="group_list brief">
                    {% for user_course in user_courses %}
                    <div class="module1_5 box">
                            <a href="{% url 'courses:course_detail' user_course.course.id %}">
                                <img width="214" height="190" class="scrollLoading" src="/media/{{ user_course.course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="../../courses/templates/course-detail.html"><h2>{{ user_course.course.name }}</h2></a>
                                <span class="fl">课时：<i class="key">{{ user_course.course.lea }}</i></span>
                                <span class="fr">学习人数：13</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ user_course.course.org }}</span>
                                <span class="star fr  notlogin" data-favid="15">{{ user_course.course.favor_num }}</span>
                            </div>
                        </div>
                    {% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}

apps/users/templates/usercenter-userfavor-.msgs.html
{% extends 'usercenter-info.html' %}
{% load static %}

{% block title %}我的收藏- 学习在线{% endblock %}

{% block bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'homepage' %}">首页</a>></li>
            <li><a href="{% url 'users:user_center' %}">个人中心</a>></li>
            <li>我的收藏</li>
        </ul>
    </div>
</section>

{% endblock %}

{% block content %}


{% endblock %}

apps/users/templates/usercenter-userfavor-course.html
{% extends 'usercenter-info.html' %}
{% load static %}

{% block title %}我的收藏- 学习在线{% endblock %}

{% block bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'homepage' %}">首页</a>></li>
            <li><a href="{% url 'users:user_center' %}">个人中心</a>></li>
            <li>我的收藏</li>
        </ul>
    </div>
</section>

{% endblock %}

{% block content %}
    <div class="right" >
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>

        <div class="personal_des permessage">

                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:fav_orgs' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:fav_teachers' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:fav_course' %}">公开课程</a></li>
                    </ul>
                </div>

                <div class="companycenter">
                    <div class="group_list brief">

                        {% for course in courses_lst%}
                        <div class="module1_5 box">
                            <a href="{% url 'courses:course_detail' course.id %}">
                                <img width="214" height="190" src="/media/{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="../../courses/templates/course-detail.html"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students_num }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.org }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
    </div>
{% endblock %}

apps/users/templates/usercenter-userfavor-orgs.html
{% extends 'usercenter-info.html' %}
{% load static %}

{% block title %}我的收藏- 学习在线{% endblock %}

{% block bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'homepage' %}">首页</a>></li>
            <li><a href="{% url 'users:user_center' %}">个人中心</a>></li>
            <li>我的收藏</li>
        </ul>
    </div>
</section>

{% endblock %}

{% block content %}
   <div class="right" >

       <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>

       <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li class="active"><a href="{% url 'users:fav_orgs' %}">课程机构</a> </li>
                    <li><a href="{% url 'users:fav_teachers' %}">授课教师 </a></li>
                    <li ><a href="{% url 'users:fav_course' %}">公开课程</a></li>
                </ul>
            </div>

            <div class="messagelist">
                {% for org in orgs_lst %}

                <div class="messages butler_list company company-fav-box">
                    <dl class="des fr">
                        <dt>
                            <a href="{% url 'orgs:org_homepage' org.id %}">
                                <img width="160" height="90" src="/media/{{ org.image }}"/>
                            </a>
                        </dt>
                        <dd>
                            <h1><a href="../../organization/templates/org-detail-homepage.html">{{ org.name }}</a></h1>
                            <div class="pic fl" style="width:auto;">

                                <img src="/static/images/authentication.png"/>
                                <img src="/static/images/gold.png"/>

                            </div>
                            <span class="c8 clear">{{ org.address }}</span>
                            <div class="delete jsDeleteFav_org"  data-favid="{{ org.id }}"></div>
                        </dd>
                    </dl>
                </div>

                {% endfor %}
            </div>
        </div>

   </div>
{% endblock %}

apps/users/templates/usercenter-userfavor-teachers.html
{% extends 'usercenter-info.html' %}
{% load static %}

{% block title %}我的收藏- 学习在线{% endblock %}

{% block bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'homepage' %}">首页</a>></li>
            <li><a href="{% url 'users:user_center' %}">个人中心</a>></li>
            <li>我的收藏</li>
        </ul>
    </div>
</section>

{% endblock %}

{% block content %}
<div class="right" >

     <div class="personal_des Releasecont">
        <div class="head">
            <h1>我的收藏</h1>
        </div>
     </div>

     <div class="personal_des permessage">

         <div class="head">
            <ul class="tab_header messagehead">
                <li><a href="{% url 'users:fav_orgs' %}">课程机构</a> </li>
                <li class="active"><a href="{% url 'users:fav_teachers' %}">授课教师 </a></li>
                <li class=""><a href="{% url 'users:fav_course' %}">公开课程</a></li>
            </ul>
        </div>

        <div class="messagelist">

            {% for teacher in teachers_lst %}
            <div class=" butler_list butler-fav-box">
                <dl class="des users">
                    <dt>
                        <a href="/org/teacher/detail/1/">
                            <img width="100" height="100" src="/media/{{ teacher.image }}"/>
                        </a>
                    </dt>

                    <dd>
                        <h1>
                            <a href="/org/teacher/detail/1/">
                                {{ teacher.name }}<span class="key">认证教师</span>
                            </a>
                        </h1>
                        <ul class="cont clearfix">
                            <li class="time">工作年限：<span>{{ teacher.work_year }}年</span></li>
                            <li class="c7">课程数：<span>{{ teacher.course_set.all.count }}</span></li>
                        </ul>
                        <ul class="cont clearfix">
                            <li class="time">工作公司：<span>{{ teacher.company }}</span></li>
                            <li class="c7">公司职位：<span>{{ teacher.work_position }}</span></li>
                        </ul>
                    </dd>
                    <div class="delete jsDeleteFav_teacher" data-favid="{{ teacher.id }}"></div>
                </dl>
            </div>
            {% endfor %}

        </div>

     </div>

 </div>
{% endblock %}