MxOnline/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from users.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static
from organization.views import TeacherListView
from django.views.static import serve
import xadmin

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    # url(r'^xadmin/', xadmin.site.urls),
    url(r'^index/$', HomePageView.as_view(), name='homepage'),
    url(r'^$', HomePageView.as_view(), name='homepage'),
    url(r'^captcha/', include('captcha.urls')),

    url(r'^user/', include('users.urls', namespace='users')),
    url(r'^course/', include('courses.urls', namespace='courses')),
    url(r'^org/', include('organization.urls', namespace='orgs')),
    url(r'^operation/', include('operation.urls', namespace='operation')),
    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),
    # ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    url(r'^ueditor/',include('DjangoUeditor.urls' )),
]

if settings.DEBUG:
    # 在开发模式下，用户上传到media文件夹的文件可以按照设定的路径查找，但仅限于开发模式；
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]
else:
    # 保证项目固定的静态文件可以正常加载,按照设定的路径查找；
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

apps/courses/urls.py
from django.conf.urls import url, include
from .views import CourseListView, CourseDetailView, CourseVideoView, VideoPlayView, CourseCommentView, AddCommentView



urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name='course_list'),  # 视频列表页
    url(r'^(?P<course_id>.*)/detail/$', CourseDetailView.as_view(), name='course_detail'),  # 课程详情
    url(r'^(?P<course_id>.*)/videos/$', CourseVideoView.as_view(), name='course_videos'),   # 课程视频列表
    url(r'^(?P<course_id>.*)/play_videos/(?P<video_id>.*)/$', VideoPlayView.as_view(), name='play_videos'), # 视频播放页面

    url(r'^(?P<course_id>.*)/comment/$', CourseCommentView.as_view(), name='course_comment'),  # 指定的课程评论列表页面
    url(r'^add_comment/$', AddCommentView.as_view(), name='add_comment'),  # 评论当前课程

]

apps/organization/urls.py
from django.conf.urls import url, include
from .views import OrgListView, TeacherListView
from .views import OrgHomePage, OrgCourseView, OrgDescriptionView, OrgTeachersView, AddFavorView, TeacherDetailView


urlpatterns = [
    #机构页面相关的url配置
    url(r'^list/$', OrgListView.as_view(), name='org_list'),    # 机构列表页
    url(r'^home/(?P<org_id>[0-9]+)/$', OrgHomePage.as_view(), name='org_homepage'), # 机构详情页主页面
    url(r'^courses/(?P<org_id>[0-9]+)/$', OrgCourseView.as_view(), name='courses'), # 机构课程
    url(r'^des/(?P<org_id>[0-9]+)/$', OrgDescriptionView.as_view(), name='description'), #机构简介
    url(r'^teachers/(?P<org_id>[0-9]+)/$', OrgTeachersView.as_view(), name='teachers'), #机构的教师列表

    #教师页面相关的url配置
    url(r'^teacher_detail/(?P<teacher_id>[0-9]+)/$', TeacherDetailView.as_view(), name='teacher_detail'),


    url(r'^add_fav/$', AddFavorView.as_view(), name='add_favor'),


]

apps/users/urls.py
from django.conf.urls import url
from .views import LoginView, logout_user, RegisterView, ActivateUserView, active_fail, active_success, ForgetPwdView, \
    ResetPwdView, UserCenterInfoView, SendEmailCodeView, ChangeEmailView, ChangePwdView, ImageUploadView, MyCourseView, \
    UserFavorCourseView, UserFavorTeachersView, UserFavorOrgsView, UserMessagesView



urlpatterns = [
    url('^login/$', LoginView.as_view(), name='login'),  # 用户登录
    url('^register/$', RegisterView.as_view(), name='register'),  # 注册新用户
    url('^logout/$', logout_user, name='logout'), # 注销当前用户
    url('^activate/(?P<code>.{16})/$', ActivateUserView.as_view(), name='activate'),#激活用户

    url('^active_failed/$', active_fail, name='active_failed'),
    url('^active_success/$', active_success, name='active_success'),

    url('^forget_pwd/$', ForgetPwdView.as_view(), name='forget_pwd'), # 登录页面忘记密码
    url('^reset_pwd/$', ResetPwdView.as_view(), name='reset_pwd'),  # 重置密码

    #在用户中心进行的相关操作
    url('^send_email_code/$', SendEmailCodeView.as_view(), name='send_email_code'),  # 发送邮箱验证码
    url('^change_email/$', ChangeEmailView.as_view(), name='change_mail'),
    url('^change_password/$', ChangePwdView.as_view(), name='change_pwd'),  # 修改密码
    url('^image_upload/$', ImageUploadView.as_view(), name='change_image'),  # 修改图片
    url('^user_course/$', MyCourseView.as_view(), name='user_course'),    # 用户学习课程

    url('^info/$', UserCenterInfoView.as_view(), name='user_center'),
    url('^favor/course/$', UserFavorCourseView.as_view(), name='fav_course'),  # 用户收藏课程
    url('^favor/orgs/$', UserFavorOrgsView.as_view(), name='fav_orgs'),  # 用户收藏机构
    url('^favor/teachers/$', UserFavorTeachersView.as_view(), name='fav_teachers'),  # 用户收藏教师
    url('^messages/$', UserMessagesView.as_view(), name='user_messages'),  # 用户消息

]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/courses/models.py
from datetime import datetime
from django.db import models
from organization.models import CourseOrg, Teacher
from DjangoUeditor.models import UEditorField
from django.utils.safestring import mark_safe


class Course(models.Model):
    name = models.CharField(max_length=50, verbose_name='课程名')
    description = models.CharField(max_length=100, verbose_name='课程描述')
    # detail = models.TextField(verbose_name='课程详情')
    # 配置ueditor
    detail = UEditorField(verbose_name='课程详情', width=600, height=300, imagePath="courses/ueditor/",
                            filePath="courses/ueditor/",default='')

    degree = models.CharField(choices=(('CJ', '初级'), ('ZJ', '中级'), ('GJ', '高级')), max_length=10)
    learn_times = models.IntegerField(default=0, verbose_name='学习时长(分钟)')
    students_num = models.IntegerField(default=0, verbose_name='学习人数')
    category = models.CharField(max_length=20, verbose_name='课程类别')
    favor_num = models.IntegerField(default=0, verbose_name='收藏数')
    org = models.ForeignKey(CourseOrg, verbose_name="所属课程机构")
    image = models.ImageField(upload_to="course/%Y/%m", verbose_name='课程图片', max_length=100)
    click_num = models.IntegerField(default=0, verbose_name='点击数')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='课程添加时间')
    teacher = models.ForeignKey(Teacher, verbose_name="授课教师", blank=True, null=True)
    recommend = models.BooleanField(default=False, verbose_name='是否推荐', max_length=2)
    has_favor = models.BooleanField(default=False, verbose_name='是否收藏')
    notice = models.CharField(default='', verbose_name='课程须知', max_length=200)
    is_banner = models.BooleanField(default=False, verbose_name='广告课程')

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name
        db_table = '课程'

    def __str__(self):
        return self.name

    def get_chap_num(self):
        return self.chapter_set.all().count()

    get_chap_num.short_description='章节数'

    def my_link(self):
        return mark_safe('<a href="https://www.baidu.com">链接</a>')
    my_link.short_description='章节数'


class Chapter(models.Model):
    name = models.CharField(max_length=50, verbose_name='章节名')
    course = models.ForeignKey(Course, verbose_name='所属课程')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='课程添加时间')

    class Meta:
        verbose_name = '章节'
        verbose_name_plural = verbose_name
        db_table = '章节'

    def __str__(self):
        return self.name


class Video(models.Model):
    name = models.CharField(max_length=50, verbose_name='视频名')
    chapter = models.ForeignKey(Chapter, verbose_name='所属章节')
    url = models.URLField(max_length=200, verbose_name='视频链接')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='课程添加时间')

    class Meta:
        verbose_name = '视频'
        verbose_name_plural = verbose_name
        db_table = '视频'

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    name = models.CharField(max_length=30, verbose_name='资料名称')
    course = models.ForeignKey(Course)
    download = models.FileField(upload_to='course/download/%Y/%m', verbose_name='下载', max_length=100)

    class Meta:
        verbose_name = '课程资源下载'
        verbose_name_plural = verbose_name
        db_table = '课程资源下载'

    def __str__(self):
        return self.name

apps/organization/models.py
from datetime import datetime

from django.db import models
from users.models import UserProfile


class City(models.Model):
    name = models.CharField(max_length=50, verbose_name='城市名称')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间', max_length=50)

    class Meta:
        verbose_name = '城市'
        verbose_name_plural = verbose_name
        db_table='城市'

    def __str__(self):
        return self.name


class CourseOrg(models.Model):
    name = models.CharField(verbose_name='课程机构', max_length=20)
    category = models.CharField(choices=(('training_org', '培训机构'), ("school", '高校'), ('personal', '个人')), max_length=20)
    image = models.ImageField(upload_to="org/%Y/%m", max_length=100, verbose_name='机构图片')
    address = models.CharField(max_length=100, verbose_name='机构详细地址')
    description = models.TextField(verbose_name='机构介绍')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    click_num = models.IntegerField(default=0, verbose_name='点击数')
    favor_num = models.IntegerField(default=0, verbose_name='收藏数')
    city = models.ForeignKey(City, verbose_name='所在城市')
    students_num = models.IntegerField(default=0, verbose_name='学生人数')
    courses_num = models.CharField(default=0, verbose_name='课程数目', max_length=5)
    has_favor = models.BooleanField(default=False, verbose_name='是否收藏')

    class Meta:
        verbose_name = '课程机构'
        verbose_name_plural = verbose_name
        db_table='课程机构'

    def __str__(self):
        return self.name

    def get_courses_num(self):
        return self.course_set.all().count()


class Teacher(models.Model):
    name = models.CharField(verbose_name='教师姓名', max_length=20)
    image = models.ImageField(verbose_name='教师图片', max_length=100, upload_to='teacher/%Y/%m')
    work_year = models.IntegerField(verbose_name='工作年限', null=True, blank=True)
    work_position = models.CharField(max_length=20, verbose_name='工作职位', null=True, blank=True)
    age = models.IntegerField(verbose_name='年龄', default=0)
    introduction = models.CharField(max_length=100, verbose_name='教师描述')
    click_num = models.IntegerField(default=0, verbose_name='点击数')
    favor_num = models.IntegerField(default=0, verbose_name='收藏数')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间', max_length=20)
    org = models.ForeignKey(CourseOrg, verbose_name='所属机构')
    gender = models.CharField(choices=(('male','男'), ('female', '女')), verbose_name='性别', max_length=10, default='')
    company = models.CharField(max_length=20, default='',verbose_name='就职公司')
    nick_name = models.CharField(default='', verbose_name='昵称', max_length=10)

    #收藏用户id，若对应的id的用户收藏了此课程，那么favor_user_id = user.id,
    # has_favor = models.BooleanField(default=False, verbose_name='会否收藏',max_length=10)
    # has_favor_user = models.ForeignKey(UserProfile, verbose_name='收藏用户', default=1)
    # favor_user_id = models.IntegerField(default=0, verbose_name='收藏用户')#

    class Meta:
        verbose_name = '讲师'
        verbose_name_plural = verbose_name
        db_table='教师'

    def __str__(self):
        return self.name

apps/courses/templates/course-comment.html
{% extends 'base.html' %}
{% load static %}
{% block title  %} {{ course.name }}| 学习在线{% endblock %}
{% block custom_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/course-comment.css' %}" />
{% endblock %}

{% block bread %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="{% url 'homepage' %}">首页</a>></li>
                <li><a href="{% url 'orgs:org_list' %}">公开课程</a>></li>
                <li><a href="{% url 'courses:course_detail' course.id %}">课程详情</a>></li>
                <li>章节信息</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}

{% block content %}
<div id="main">

    {# 课程详情信息题头 #}
	<div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_times }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.students_num }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
            </div>
	</div>


	<div class="course-info-main clearfix w has-progress">
		<div class="info-bar clearfix">
		    <div class="content-wrap clearfix">

                {# 页面左侧内容 #}
		            <div class="content">

                        {# nav导航栏 #}
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'courses:course_videos' course.id %}"><span>章节</span></a></li>
                                <li><a id="commentOn" class="active" href="{% url 'courses:course_comment' course.id %}"><span>评论</span></a></li>
                            </ul>
                        </div>

                        <!--发布评论区域-->
                        <div id="js-pub-container" class="issques clearfix js-form">

                            <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                                <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" ></textarea>
                            </div>
                            <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                            <p class="global-errortip js-global-error"></p>
                        </div>

                        {# 用户评论列表 #}
                        <div id="course_note">
                            <ul class="mod-post" id="comment-list">

                                {% for comment in all_comments %}
                                <li class="post-row">
                                    <div class="media">
                                        <span target="_blank"><img src='/media/{{ comment.user.image }}' width='40' height='40' /></span>
                                    </div>

                                    <div class="bd">
                                        <p class="cnt">{{ comment }}</p>

                                        <div class="footer clearfix">
                                            <a href="#"> <span class="l">{{ comment.user.nick_name }}</span></a>
                                            <span title="创建时间" class="l timeago">{{ comment.add_time }}</span>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>

                </div>

                {# 页面右侧内容 #}
		        		<div class="aside r">
                            <div class="bd">

                                {# 资料下载box #}
                                <div class="box mb40">
                                    <h4>资料下载</h4>
                                    <ul class="downlist">
                                        {% for dowmload_file in course.courseresource_set.all %}
                                        <li>
                                            <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ dowmload_file.name }}</span>
                                            <a href="/media/{{ dowmload_file.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                                        </li>
                                        {% endfor %}

                                    </ul>
                                </div>

                                {# 讲师详情box #}
                                <div class="box mb40">
                                    <h4>讲师提示</h4>
                                    <div class="teacher-info">
                                        <a href="/u/315464/courses?sort=publish" target="_blank">
                                            <img src='/media/{{ course.teacher.image }}' width='80' height='80' />
                                        </a>
                                        <span class="tit">
                                        <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
                                        </span>

                                        <span class="job">{{ course.teacher.work_position }}</span>
                                    </div>

                                    <div class="course-info-tip">
                                        <dl class="first">
                                            <dt>课程须知</dt>
                                            <dd class="autowrap">{{ course.notice }}</dd>
                                        </dl>
                                        <dl>
                                            <dt>老师告诉你能学到什么？</dt>
                                            <dd class="autowrap">{{ course.description }}</dd>
                                        </dl>
                                    </div>

                                </div>

                                {# 同学课程 #}
                                <div class="cp-other-learned  js-comp-tabs">
                                    <div class="cp-header clearfix">
                                        <h2 class="cp-tit l">该课的同学还学过</h2>
                                    </div>

                                    <div class="cp-body">
                                        <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                            <!-- img 200 x 112 -->
                                            <ul class="other-list">

                                                {% for course in recommended_courses %}
                                                <li class="curr">
                                                    <a href="{% url 'courses:course_detail' course.id %}" target="_blank">
                                                        <img src="/media/{{ course.image }}" alt="django与vuejs实战项目2">
                                                        <span class="name autowrap">{{ course.name }}</span>
                                                    </a>
                                                </li>
                                                {% endfor %}

                                            </ul>
                                        </div>
                                        <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                            <ul class="other-list">
                                                <li class="curr">
                                                    <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                        <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                                        <span class="name autowrap">Java工程师</span>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>

		</div>
	    </div>

        <div class="clear">

        </div>

    </div>

</div>

{% endblock %}

{% block custom_js %}
<script type="text/javascript">
    //添加评论
    $('#js-pl-submit').on('click', function(){
        var comments = $("#js-pl-textarea").val()
        if(comments == ""){
            alert("评论不能为空")
            return
        }

        $.ajax({
            cache: false,
            type: "POST",
            url:"{% url 'courses:add_comment' %}",
            data:{'course_id':{{ course.id }}, 'comments':comments},
            async: true,
            beforeSend:function(xhr, settings){
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function(data) {
                if(data.status == 'fail'){
                    if(data.msg == '用户未登录'){
                        window.location.href="{% url 'users:login' %}";
                    }else{
                        alert(data.msg)
                    }

                }else if(data.status == 'success'){
                     alert(data.msg)
                    window.location.reload();//刷新当前页面.
                }
            },
        });
    });

</script>
{% endblock %}

apps/courses/templates/course-detail.html
{% extends 'base.html' %}

{% block title  %}课程详情 | 学习在线{% endblock %}

{% block custom_css %}
<style>
.thumbnail{
    margin-right: 20px!important;
    margin-top: 10px!important;
    width: 190px!important;
    border: none;
}
</style>

{% endblock %}
{% block bread %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="{% url 'homepage' %}">首页</a>></li>
                <li><a href="{% url 'orgs:org_list' %}">公开课程</a>></li>
				<li>课程详情</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}

{% block content %}

    {# 课程介绍与课程机构 #}
    <section>
	<div class="wp">
		<div class="groupPurchase_detail detail">
			<div class="toppro">
				<div class="left">
					<div class="picbox">
						<div class="tb-booth tb-pic">
							<img width="440" height="445" src="/media/{{ course.image }}" class="jqzoom" style="border-radius: 10px"/>
						</div>

					</div>
					<div class="des">
						<h1 title="django 从入门到精通体验开始了">{{ course.name }}</h1>
						<span class="key">
                            {{ course.description }}
                        </span>
						<div class="prize">
							<span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
							<span class="fr">学习人数：{{ course.students_num }}</span>
						</div>
						<ul class="parameter">
							<li><span class="pram word3">时&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;长：</span><span class="desc_content">{{ course.learn_times }}</span></li>
                            <li><span class="pram word3">章&nbsp;节&nbsp;数：</span><span class="desc_content">{{ course.chapter_set.all.count }}</span></li>
                            <li><span class="pram word3">课程类别：</span><span class="desc_content">{{ course.category }}</span></li>
							<li class="piclist"><span class="pram word4">学习用户：</span>
                                {% for user in user_list %}
                                <span class="pic"><img width="40" height="40" src="/media/{{ user.image }}"/></span>
                                {% endfor %}
							</li>
						</ul>
						<div class="btns">
							<button class="btn btn-success" id="jsLeftBtn" style="width: 80px">
                                <span style="margin-top: 200px">{% if course_favor %}
                                    已收藏
                                {% else %}
                                    收藏
                                {% endif %}</span>
                            </button>
                        <a style="color: white" href="{% url 'courses:course_videos' course.id %}">

                                <button class="btn btn-danger">开始学习</button>
                        </a>
						</div>
					</div>
                    <div class="group-share-box">
                        <div class="bdsharebuttonbox"
                             data-text="django开始了"
                             data-desc="我在#慕课网#发现了"
                             data-comment=""
                             data-url="/group/groupdetail/15/">
                            <span class="fl">分享到：</span>
                            <a href="#" class="bds_more" data-cmd="more"></a>
                            <a title="分享到QQ空间" href="#" class="bds_qzone" data-cmd="qzone"></a>
                            <a title="分享到新浪微博" href="#" class="bds_tsina" data-cmd="tsina"></a>
                            <a title="分享到腾讯微博" href="#" class="bds_tqq" data-cmd="tqq"></a>
                            <a title="分享到人人网" href="#" class="bds_renren" data-cmd="renren"></a>
                            <a title="分享到微信" href="#" class="bds_weixin" data-cmd="weixin"></a>
                        </div>
                    </div>
				</div>

				<div class="right">
                    <div class="row">
                    <div class="head">授课机构</div>
                        <div class="thumbnail" style="margin-left:30px;height: 290px">
                        <a href="{% url 'orgs:org_homepage' course.org.id %}">
                            <img src="/media/{{ course.org.image }}" alt="...">
                        </a>
                          <div class="caption" style="font-size: 14px">
                              <span class="glyphicon glyphicon-user"> 机构名：<span class="desc_content">{{ course.org.name }}</span></span><br>
                              <span class="glyphicon glyphicon-tags"> 类 别：<span class="desc_content">{{ course.org.get_category_display }}</span></span><br>
                            <span class="glyphicon glyphicon-hand-right"> 点击量：<span class="desc_content">{{ course.org.click_num }}</span></span><br>
                            <span class="glyphicon glyphicon-facetime-video"> 课程数：<span class="desc_content">{{ course.org.course_set.all.count }}</span></span><br>
                              <span class="glyphicon glyphicon-user"> 教师数：<span class="desc_content">{{ course.org.teacher_set.all.count }}</span></span><br>
                              <span class="glyphicon glyphicon-map-marker"> 地 区：<span class="desc_content">{{ course.org.address }}</span></span><br>
                          </div>
                        </div>
                  </div>
				</div>
			</div>
		</div>
	</div>
</section>

    {# 课程章节详情 #}
    <section>
	<div class="wp">
		<div class="list groupPurchase_detail_pro">

        {# 课程详情 #}
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active">课程详情</li>
					</ul>
				</div>
				<div class="tab_cont tab_cont1">

                    {% autoescape off %}
					<p>{{ course.detail }}</p>
                    {% endautoescape %}

				</div>
			</div>

        {# 相关课程推荐 #}
			<div class="right layout">
                <div class="row">
				<div class="head" style="width: 210px;margin-left: 15px">相关课程推荐</div>
                {% ifequal related_course '' %}
                {% else %}

                    <div class="row" style="height: 200px">
                        <div class="thumbnail" style="height: 100px;margin-left: 30px">
                          <a target="_blank" href="{% url 'courses:course_detail' related_course.id %}">
                              <img width="220" height="200" class="scrollLoading" src="/media/{{ related_course.image }}">
                          </a>

                          <div class="caption" style="text-align: center">
                                <h4 class="">{{ related_course.name }}</h4>
                                <span class="">学习时长(分钟)：<i class="key">{{ related_course.learn_times }}</i></span>
                          </div>
                        </div>
                    </div>
                    </div>
                {% endifequal %}

			</div>

		</div>
	</div>
    </section>

{% endblock %}

{% block custom_js %}
<script type="text/javascript">
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'orgs:add_favor' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="../../../templates/login.html";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('#jsLeftBtn').on('click', function(){
    add_fav($(this), {{ course.id }}, 1);
});

$('#jsRightBtn').on('click', function(){
    add_fav($(this), {{ course.org.id }}, 3);
});


</script>
{% endblock %}

apps/courses/templates/course_not_exist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>错误页面</title>
</head>
<body>
<h1>您所查询的课程不存在</h1>

</body>
</html>