MxOnline/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from users.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static
from organization.views import TeacherListView
from django.views.static import serve
import xadmin

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    # url(r'^xadmin/', xadmin.site.urls),
    url(r'^index/$', HomePageView.as_view(), name='homepage'),
    url(r'^$', HomePageView.as_view(), name='homepage'),
    url(r'^captcha/', include('captcha.urls')),

    url(r'^user/', include('users.urls', namespace='users')),
    url(r'^course/', include('courses.urls', namespace='courses')),
    url(r'^org/', include('organization.urls', namespace='orgs')),
    url(r'^operation/', include('operation.urls', namespace='operation')),
    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),
    # ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    url(r'^ueditor/',include('DjangoUeditor.urls' )),
]

if settings.DEBUG:
    # 在开发模式下，用户上传到media文件夹的文件可以按照设定的路径查找，但仅限于开发模式；
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]
else:
    # 保证项目固定的静态文件可以正常加载,按照设定的路径查找；
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

apps/courses/urls.py
from django.conf.urls import url, include
from .views import CourseListView, CourseDetailView, CourseVideoView, VideoPlayView, CourseCommentView, AddCommentView



urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name='course_list'),  # 视频列表页
    url(r'^(?P<course_id>.*)/detail/$', CourseDetailView.as_view(), name='course_detail'),  # 课程详情
    url(r'^(?P<course_id>.*)/videos/$', CourseVideoView.as_view(), name='course_videos'),   # 课程视频列表
    url(r'^(?P<course_id>.*)/play_videos/(?P<video_id>.*)/$', VideoPlayView.as_view(), name='play_videos'), # 视频播放页面

    url(r'^(?P<course_id>.*)/comment/$', CourseCommentView.as_view(), name='course_comment'),  # 指定的课程评论列表页面
    url(r'^add_comment/$', AddCommentView.as_view(), name='add_comment'),  # 评论当前课程

]

apps/organization/urls.py
from django.conf.urls import url, include
from .views import OrgListView, TeacherListView
from .views import OrgHomePage, OrgCourseView, OrgDescriptionView, OrgTeachersView, AddFavorView, TeacherDetailView


urlpatterns = [
    #机构页面相关的url配置
    url(r'^list/$', OrgListView.as_view(), name='org_list'),    # 机构列表页
    url(r'^home/(?P<org_id>[0-9]+)/$', OrgHomePage.as_view(), name='org_homepage'), # 机构详情页主页面
    url(r'^courses/(?P<org_id>[0-9]+)/$', OrgCourseView.as_view(), name='courses'), # 机构课程
    url(r'^des/(?P<org_id>[0-9]+)/$', OrgDescriptionView.as_view(), name='description'), #机构简介
    url(r'^teachers/(?P<org_id>[0-9]+)/$', OrgTeachersView.as_view(), name='teachers'), #机构的教师列表

    #教师页面相关的url配置
    url(r'^teacher_detail/(?P<teacher_id>[0-9]+)/$', TeacherDetailView.as_view(), name='teacher_detail'),


    url(r'^add_fav/$', AddFavorView.as_view(), name='add_favor'),


]

apps/users/urls.py
from django.conf.urls import url
from .views import LoginView, logout_user, RegisterView, ActivateUserView, active_fail, active_success, ForgetPwdView, \
    ResetPwdView, UserCenterInfoView, SendEmailCodeView, ChangeEmailView, ChangePwdView, ImageUploadView, MyCourseView, \
    UserFavorCourseView, UserFavorTeachersView, UserFavorOrgsView, UserMessagesView



urlpatterns = [
    url('^login/$', LoginView.as_view(), name='login'),  # 用户登录
    url('^register/$', RegisterView.as_view(), name='register'),  # 注册新用户
    url('^logout/$', logout_user, name='logout'), # 注销当前用户
    url('^activate/(?P<code>.{16})/$', ActivateUserView.as_view(), name='activate'),#激活用户

    url('^active_failed/$', active_fail, name='active_failed'),
    url('^active_success/$', active_success, name='active_success'),

    url('^forget_pwd/$', ForgetPwdView.as_view(), name='forget_pwd'), # 登录页面忘记密码
    url('^reset_pwd/$', ResetPwdView.as_view(), name='reset_pwd'),  # 重置密码

    #在用户中心进行的相关操作
    url('^send_email_code/$', SendEmailCodeView.as_view(), name='send_email_code'),  # 发送邮箱验证码
    url('^change_email/$', ChangeEmailView.as_view(), name='change_mail'),
    url('^change_password/$', ChangePwdView.as_view(), name='change_pwd'),  # 修改密码
    url('^image_upload/$', ImageUploadView.as_view(), name='change_image'),  # 修改图片
    url('^user_course/$', MyCourseView.as_view(), name='user_course'),    # 用户学习课程

    url('^info/$', UserCenterInfoView.as_view(), name='user_center'),
    url('^favor/course/$', UserFavorCourseView.as_view(), name='fav_course'),  # 用户收藏课程
    url('^favor/orgs/$', UserFavorOrgsView.as_view(), name='fav_orgs'),  # 用户收藏机构
    url('^favor/teachers/$', UserFavorTeachersView.as_view(), name='fav_teachers'),  # 用户收藏教师
    url('^messages/$', UserMessagesView.as_view(), name='user_messages'),  # 用户消息

]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/users/forms.py
from django import forms
from captcha.fields import CaptchaField


class LoginForms(forms.Form):
    password = forms.CharField(min_length=6, max_length=20, label='密码', required=True)
    username = forms.CharField(min_length=1, required=True, label='用户名', widget=forms.Textarea)





from django.forms import ValidationError
from users.models import UserProfile


class RegisterForms(forms.Form):
    username = forms.CharField(min_length=2, max_length=30,
                               error_messages={'required': '用户名不能为空', 'min_length': '用户名至少为两位'})
    password1 = forms.CharField(min_length=6, max_length=12,
                                error_messages={'required': '密码不能为空', 'min_length': '密码至少为两位'})
    password2 = forms.CharField(min_length=6, max_length=12,
                                error_messages={'required': '密码不能为空', 'min_length': '密码名至少为两位'})
    captcha = CaptchaField()

    def clean_username(self):
        username = self.cleaned_data['username'].strip()
        if UserProfile.objects.filter(username=username):
            raise ValidationError("用户已注册")
        return username

    def clean(self):
        """密码一致性检测"""
        if self.cleaned_data.get('password1', '') == self.cleaned_data.get('password2', ''):
            return self.cleaned_data
        else:
            raise ValidationError("密码不一致")


class ForgetPwdForms(forms.Form):
    username = forms.CharField(max_length=30, error_messages={'required': '用户名不能为空'})
    captcha = CaptchaField()

    def clean_username(self):
        username = self.cleaned_data['username'].strip()
        if not UserProfile.objects.filter(username=username):
            raise ValidationError("用户不存在")
        return username


class ResetPwdForms(forms.Form):
    password1 = forms.CharField(min_length=6, max_length=30)
    password2 = forms.CharField(min_length=6, max_length=30)
    # username = forms.CharField(max_length=30)

    def clean(self):
        """密码一致性检测"""
        if self.cleaned_data.get('password1', '') == self.cleaned_data.get('password2', ''):
            return self.cleaned_data

        else:
            raise ValidationError("密码不一致")


class ModifyEmailForm(forms.Form):
    email = forms.EmailField(max_length=30, min_length=3)
    code = forms.CharField(min_length=4, max_length=4)

    # # 可以使用全局钩子验证
    # def clean(self):
    #     from apps.users.models import EmailVerifyRecord
    #     if not EmailVerifyRecord.objects.filter(email=self.email, code=self.code,send_type='change_email'):
    #         raise ValidationError('邮箱或验证码不匹配')
    #     else:
    #         return self.cleaned_data



class UploadImageForm(forms.Form):
    image = forms.ImageField(max_length=100)

templates/activate_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>激活成功</title>
</head>
<body>
<h1>激活成功,请点击下面的链接前往登录界面</h1>
<a href="http://127.0.0.1:8000/users/login/">http://127.0.0.1:8000/users/login/</a>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html>
{% load static %}


<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %} | 学习在线{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

    <style>
        {#  导航条显示相关自定制,包括字体颜色显示和悬浮显示　　#}
        .navbar-inverse .navbar-nav > li > a{
        font-size: 16px;
        }
        {#自定制logo#}
        .logo_img{
            margin-top: 10px;
        }
        .navbar-inverse .navbar-nav > li > a{
            color: white;
        }
        .navbar-nav > li > a:hover{
            color:greenyellow !important;
        }

        .media-left{
            padding-right: 30px;
        }

    </style>
    {% block custom_css %}{% endblock %}

</head>
<body>

{#导航条设置#}
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <a href="{% url 'homepage' %}">
            <img class="logo_img" src="{% static 'images/logo.png' %}">
        </a>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
{#        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>#}
{#        <li><a href="#" class="">主页</a></li>#}
        <li><a href="{% url 'courses:course_list' %}" class="active" >公开课</a></li>
        <li><a href="{% url 'orgs:org_list' %}" >课程机构</a></li>
        <li><a href="{% url 'teacher_list' %}">授课教师</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
           <select id="jsSelectOption" style="height: 34px;border-radius: 4px">
                <option value="course" selected>课程</option>
                <option value="org">机构</option>
                <option value="teacher">教师</option>
            </select>
          <input type="text" class="form-control" placeholder="Search" id="search_keywords">
        </div>
        <input type="button" class="btn btn-default" id="search_btn" value="查询">
      </form>

      <ul class="nav navbar-nav navbar-right">
       {% if request.user.is_authenticated %}
            <li><a class="personcenter fl" href="{% url 'users:user_center' %}">进入个人中心&nbsp;&nbsp;
                <span style="font-size: 13px">{{ user.username }}</span>&nbsp;&nbsp;
                <img src="/media/{{ user.image }}" width="30px"></a></li>
           <li><a class="fr" href="{% url 'users:logout' %}">退出</a></li>

        {% else %}
             <li><a href="{% url 'users:login' %}">登录</a></li>
             <li><a href="{% url 'users:register' %}">注册</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<!--crumbs start-->
{% block bread %}{% endblock %}
{% block content %}
{% endblock %}

{#　footer　#}
<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="{% static 'images/logo.png' %}" style="margin-top: 30px"/>
                </a><span style="display: block;font-size: 13px;margin-top: 10px">帮助有志向的年轻人通过努力学习获得体面的工作和生活。</span></li>
                <li class="third"><img class="fl" src="/static/images/tell.png"/><p class="tell">33333333</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear" style="text-align: center">
            <span class="">在线学习  保留所有权利</span><br>
            <span class="">https://www.cnblogs.com/fqh202</span><br>
            <span class="">copyright 2018 ICP备案证书号：鄂ICP备1212号-2</span>
        </div>
    </div>
</footer>


<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>

<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% block custom_js %}
<script>

$('#search_btn').click(function () {
    var type = $('#jsSelectOption').attr('value'),
        keywords = $('#search_keywords').val(),
        request_url = '';
    if(keywords == ""){
        return
    }
    if(type == "course"){
        request_url = "/course/list?keywords="+keywords

    }else if(type == "teacher"){
        request_url = "/teacher/list?keywords="+keywords

    }else if(type == "org"){
        request_url = "/org/list?keywords="+keywords
    }
    window.location.href=request_url
})

</script>

{% endblock %}

</body>
</html>

templates/header_copy.html
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>33333333</b></p></div>
					<!--登录后跳转-->
                    {% if request.user.is_authenticated %}
						<div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.nick_name }}<img class="down fr" src="/static/images/top_down.png"/></dd>
                                <dt><img width="20" height="20" src="/media/{{ user.image }}"/></dt>
                            </dl>

                            <a href="{% url 'users:user_messages' %}">
                                <div class="msg-num"> <span id="MsgNum">{{ request.user.get_unread_msg_num }}</span></div>
                            </a>

                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="/media/{{ user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ user.mobile }}</h2>
	                                    <p>{{ user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:user_center' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'users:logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'users:register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>
                    {% endif %}
				</div>
			</div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'homepage' %}"><img class="fl" src="/static/images/logo.jpg"/></a>

                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="/static/images/search_btn_1.png"/>
                    </div>

                </div>
            </div>

			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li class="{% ifequal request.path|slice:':6' '/index' %}active{% endifequal %}" ><a href="{% url 'homepage' %}">首页</a></li>

							<li class="{% ifequal request.path|slice:':8' '/courses' %}active{% endifequal %}">
								<a href="{% url 'courses:course_list' %}">
									公开课<img class="hot" src="/static/images/nav_hot.png">
								</a>
							</li>

							<li class="{% ifequal request.path|slice:':9' "/teacher/" %}active{% endifequal %}">
                                <a href="{% url 'teacher_list' %}">授课教师</a>
                            </li>

							<li class="{% ifequal request.path|slice:':10' "/org/list/" %}active{% endifequal %} ">
                                <a href="{% url 'orgs:org_list' %}">授课机构</a>
                            </li>
						</ul>
					</div>
				</div>
			</nav>
		</div>

    </header>
</section>

templates/index.html
{% extends 'base.html' %}

{% block title  %}学习在线{% endblock %}

{% block custom_css %}

{% endblock %}

{% block content %}

    {#  轮播图 #}
    <div class="banner">
        <div class="wp">
            <div class="fl">
                <div class="imgslide">
                    <ul class="imgs">
                        {% for banner in banners %}
                        <li>
                            <a href="{{ banner.url }}" target="_blank">
                                <img width="1200" height="478" src="/media/{{ banner.image }}" />
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
        </div>
	</div>

	<section>
		<div class="container">

			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="/static/images/feature1.png"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="/static/images/feature2.png"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="/static/images/feature3.png"/>
					<p class="center">名师授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="/static/images/feature4.png"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>

    {# 部分显示公开课程列表 #}
	<section>
		<div class="container">
        <h1 class="section_header">入门课程</h1>
			<div class="row">
				<div class="col-md-3">

                    <img width="228" height="463" src="/static/images/module1_1.jpg"/>
                    <p class="fisrt_word">名师授课<br/>专业权威</p>
                    <a class="fisrt_word_1" href="{% url 'courses:course_list' %}">查看更多课程</a>
                </div>


                 <div class="col-md-9">
                    <div class="row">
                          {% for course in all_courses  %}
                          <div class="col-md-3">
                            <div class="thumbnail">

                                 <a href="{% url 'courses:course_detail' course.id %}">
                                     <img width="233" height="190" src="/media/{{ course.image }}"/>
                                 </a>

                              <div class="caption">
                                <h3 style="font-size: 18px">{{ course.name }}</h3>
                                  <span>{{ course.get_degree_display }}</span>
                                  <span class="glyphicon glyphicon-facetime-video gl_str"></span>
                                  <span class="">{{ course.learn_times }}分钟</span>&nbsp;
                                  <span class="glyphicon glyphicon-user gl_str"></span>
                                  <span>{{ course.students_num }}人</span>

                              </div>

                            </div>
                          </div>
                        {% endfor %}

                    </div>
                 </div>

				</div>
			</div>
	</section>

    <hr>


    {# 课程机构 #}
	<section>
		<div class="container">
        <h1 class="section_header">课程机构</h1>
			<div class="row">

				<div class="col-md-3">
						<img width="228" height="463" src="/static/images/module3_1.jpg"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p><br>
						<a class="fisrt_word_1" href="{% url 'orgs:org_list' %}">查看更多机构 ></a>
                </div>

                  <div class="col-md-9">
                    <div class="row">
                       {% for org in all_orgs %}
                          <div class="col-md-3">
                            <div class="thumbnail org_list">

                              <a href="{% url 'orgs:org_homepage' org.id %}">
                                    <img style="width: 164px;height: 60px;border: solid 1px seashell" src="/media/{{ org.image }}"/>
                                </a>

                              <div class="caption">

                                <h3 style="font-size: 18px">{{ course.name }}</h3>
                                  <span class="glyphicon glyphicon-bookmark">&nbsp;{{ org.name }}</span><br>
                                  <span class="glyphicon glyphicon-home">&nbsp;{{ org.address }}</span>
                              </div>

                            </div>
                          </div>
                        {% endfor %}
                    </div>
                 </div>
				</div>
			</div>
	</section>
    <br>

{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>

{% load static %}
{% load my_tag %}

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}登录 | 学习在线{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/login.css">
    {% block custom_css %}{% endblock %}

</head>
<body>
<div class="dialog" id="jsDialog">
<!--提示弹出框-->
<div class="successbox dialogbox" id="jsSuccessTips">
    <h1>成功提交</h1>
    <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
    <div class="cont">
        <h2>您的需求提交成功！</h2>
        <p></p>
    </div>
</div>
<div  class="noactivebox dialogbox" id="jsUnactiveForm" >
    <h1>邮件验证提示</h1>
    <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
    <div class="center">
        <img src="/static/images/send.png"/>
        <p>我们已经向您的邮箱<span class="green" id="jsEmailToActive">12@13.com</span>发送了邮件，<br/>为保证您的账号安全，请及时验证邮箱</p>
        <p class="a"><a class="btn" id="jsGoToEmail" target="_blank" href="http://mail.qq.com">去邮箱验证</a></p>
        <p class="zy_success upmove"></p>
        <p style="display: none;" class="sendE2">没收到，您可以查看您的垃圾邮件和被过滤邮件，也可以再次发送验证邮件（<span class="c5c">60s</span>）</p>
        <p class="sendE">没收到，您可以查看您的垃圾邮件和被过滤邮件，<br/>也可以<span class="c5c green" id="jsSenEmailAgin" style="cursor: pointer;">再次发送验证邮件</span></p>
    </div>
</div>
</div>
<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">学习在线，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>33333333</span></li>
                <li class="active"><a href="{% url 'users:login' %}">[登录]</a></li>
                <li><a href="{% url 'users:register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="index.html"></a>
                <h1>{% block tag %}用户登录{% endblock %}</h1>
                <a class="index-font" href="">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                            <li><a href=""><img width="483" height="472" src="/static/images/mysql.jpg" /></a></li>
                            <li><a href=""><img width="483" height="472" src="/static/images/mysql.jpg" /></a></li>
                            <li><a href=""><img width="483" height="472" src="/static/images/mysql.jpg" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>

            {% block content %}
            <div class="fl form-box">
                <h2>帐号登录</h2>

                <form action="{% url 'users:login' %}" method="post" autocomplete="on">

                    <div class="form-group marb20 {% if login_form.errors.username %}errorput{% endif %}" >
                        <label>用&nbsp;户&nbsp;名</label>
                        <input name="username" id="account_l" type="text" placeholder="手机号/邮箱" value="" />
                    </div>

                    <div class="form-group marb8 {% if login_form.errors.password %}errorput{% endif %}">
                        <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                        <input name="password" id="password_l" type="password" placeholder="请输入您的密码" />
                    </div>

                    <div class="error btns login-form-tips" id="">
                        {{ msg }}
                    </div>

                     <div class="auto-box marb38">
                        <a class="fr" href="{% url 'users:forget_pwd' %}">忘记密码？</a>
                     </div>

                     <input class="btn btn-green"  type="submit" value="立即登录 > " />
                    {% csrf_token %}
                </form>

                <p class="form-p">没有学习在线帐号？<a href="{% url 'users:register' %}">[立即注册]</a></p>
            </div>
            {% endblock %}

        </div>
    </div>
</section>
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/login.js"  type="text/javascript"></script>
{% block custom_js %}{% endblock %}
</body>
</html>

templates/register_code_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>激活码有误</title>
</head>
<body>
<h1>激活码有误，请确认</h1>

</body>
</html>

templates/send_email_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册成功</title>
</head>
<body>
<h1>邮件发送成功，请前往您的邮箱激活,您注册的邮箱用户名：{{ email }}！</h1>

</body>
</html>

templates/text.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        p{
            text-align: left;
        }

        div{
            border: solid 1px red;
            text-align: center;
            width: 300px;
        }
        a{
        }
    </style>
</head>
<body>

<div>
    <p><a>hello_world</a></p>
</div>

</body>
</html>

templates/video_not_exist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>错误页面</title>
</head>
<body>
<h1>您所查询的课程视频不存在</h1>

</body>
</html>